import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://qa-buy.transfi.com/?apiKey=2ybWAQ398nDwXPla');
  await page.getByRole('button', { name: 'Buy BTC' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('vasanthkumar744896@gmail.com');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.locator('#pin-input-1-0').click();
  await page.locator('#pin-input-1-0').press('NumLock');
  await page.locator('#pin-input-1-0').fill('8');
  await page.locator('#pin-input-1-1').fill('6');
  await page.locator('#pin-input-1-2').fill('0');
  await page.locator('#pin-input-1-3').fill('5');
  await page.locator('#pin-input-1-4').fill('2');
  await page.locator('#pin-input-1-5').fill('2');
  await page.locator('iframe[name="c-xeht2h8c49s"]').contentFrame().locator('tr:nth-child(3) > td').first().click();
  await page.locator('iframe[name="c-xeht2h8c49s"]').contentFrame().locator('tr:nth-child(3) > td').first().click();
  await page.locator('iframe[name="c-xeht2h8c49s"]').contentFrame().locator('tr:nth-child(3) > td:nth-child(2)').click();
  await page.locator('iframe[name="c-xeht2h8c49s"]').contentFrame().locator('tr:nth-child(3) > td').first().click();
  await page.locator('iframe[name="c-xeht2h8c49s"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-xeht2h8c49s"]').contentFrame().locator('tr:nth-child(2) > td').first().click();
  await page.locator('iframe[name="c-xeht2h8c49s"]').contentFrame().locator('.rc-imageselect-tile').first().click();
  await page.locator('iframe[name="c-xeht2h8c49s"]').contentFrame().locator('tr:nth-child(2) > td:nth-child(2)').click();
  await page.locator('iframe[name="c-xeht2h8c49s"]').contentFrame().locator('tr:nth-child(3) > td:nth-child(2)').click();
  await page.locator('iframe[name="c-xeht2h8c49s"]').contentFrame().locator('tr:nth-child(3) > td').first().click();
  await page.locator('iframe[name="c-xeht2h8c49s"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-xeht2h8c49s"]').contentFrame().locator('tr:nth-child(3) > td:nth-child(2)').click();
  await page.locator('iframe[name="c-xeht2h8c49s"]').contentFrame().locator('tr:nth-child(2) > td:nth-child(2)').click();
  await page.locator('iframe[name="c-xeht2h8c49s"]').contentFrame().locator('tr:nth-child(2) > td:nth-child(3)').click();
  await page.locator('iframe[name="c-xeht2h8c49s"]').contentFrame().locator('tr:nth-child(3) > td:nth-child(3)').click();
  await page.locator('iframe[name="c-xeht2h8c49s"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-xeht2h8c49s"]').contentFrame().locator('tr:nth-child(2) > td:nth-child(3)').click();
  await page.locator('iframe[name="c-xeht2h8c49s"]').contentFrame().locator('tr:nth-child(2) > td:nth-child(2)').click();
  await page.locator('iframe[name="c-xeht2h8c49s"]').contentFrame().locator('tr:nth-child(2) > td').first().click();
  await page.locator('iframe[name="c-xeht2h8c49s"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-xeht2h8c49s"]').contentFrame().locator('tr:nth-child(4) > td:nth-child(2)').click();
  await page.locator('iframe[name="c-xeht2h8c49s"]').contentFrame().locator('tr:nth-child(3) > td:nth-child(2)').click();
  await page.locator('iframe[name="c-xeht2h8c49s"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-xeht2h8c49s"]').contentFrame().getByRole('button', { name: 'Get a new challenge' }).click();
  await page.locator('iframe[name="c-xeht2h8c49s"]').contentFrame().locator('.rc-imageselect-tile').first().click();
  await page.locator('iframe[name="c-xeht2h8c49s"]').contentFrame().locator('tr:nth-child(3) > td').first().click();
  await page.locator('iframe[name="c-xeht2h8c49s"]').contentFrame().locator('tr:nth-child(2) > td:nth-child(2)').click();
  await page.locator('iframe[name="c-xeht2h8c49s"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.getByRole('textbox', { name: 'Wallet address' }).click();
  await page.getByRole('textbox', { name: 'Wallet address' }).click({
    button: 'right'
  });
  await page.getByRole('textbox', { name: 'Wallet address' }).click();
  await page.getByRole('textbox', { name: 'Wallet address' }).fill('3J98t1WpEZ73CNmQviecrnyiWrnqRhWNLy');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.locator('div').filter({ hasText: /^SEPA Bank Transfer$/ }).getByRole('img').click();
  await page.getByText('SEPA Bank Transfer').click();
  await page.locator('div').filter({ hasText: /^SEPA Bank Transfer$/ }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
});